### ISSUE TITLE
Use Case documentation

### ISSUE THREAD

**Issue by FurKay00** [SE-TINF22B6/DHBWhub#138]
### Description
In order to display the use cases of our website, we need to revise our srs to make it even more understandable for new users.

### Tasks
I want this concrete feature because it helps us focus on the main components of our project as well as keeping the user well informed about the use cases and sequence diagrams. We need to simplify if possible and be more clear.
These are the following Use Cases :

- [x] Browsing Homepage without Login
- [x] Creating an Account
- [x] Signing in
- [x] Account Management
   - [x] Profile personalization
   - [x] 3rd Party Login 
- [x] Website Activities
   - [x] Browse sections or personalized feed
   - [x] Calendar customization
   - [x] Event management
   - [x] Check Notifications  (Mockup needed)
   - [x] Search bar on the homepage (Mockup needed)
- [x] FAQ/ Issue report (Mockup needed)
- [x] User Interaction
   - [x] Friendlist administration (+ Friend Request)
   - [x] Post Interaction (Comments, Sharing, Likes)
