### ISSUE TITLE
🏭 Saved posts

### ISSUE THREAD

**Issue by FurKay00** [SE-TINF22B6/DHBWhub#262]
### Description
Users should be able to save posts from other users

### Tasks
I want this concrete feature because users should bookmark important post so that they can either view it later or save it for other purposes. 
These are the following criteria:

- [ ] Save-Post button functions correctly
- [ ] Mockup for Saved-Posts component
- [ ] Implementation in React
