### ISSUE TITLE
🏭 Calendar and Events

### ISSUE THREAD

**Issue by FurKay00** [SE-TINF22B6/DHBWhub#263]
### Description
Users should be able to view a calendar containing centralized events.

### Tasks
I want this concrete feature because users should be informed about important or interesting events concerning students. Clicking one event in the calendar redirects to a more detailed event post.
These are the following criteria:

- [ ] Calendar and Event mockup
- [ ] Embedding map-elements in the database and in the event post
- [ ] Implementation in React
