### ISSUE TITLE
🏭 Notifications

### ISSUE THREAD

**Issue by FurKay00** [SE-TINF22B6/DHBWhub#264]
### Description
A user should be able to receive notifications concerning them or other connected topics.

### Tasks
I want this concrete feature because it is important to notice the user if there have been new activities affecting them.
These are the following criteria:

- [x] Mockup for notification list and arrangement
- [x] Discussing, how to implement this on the database side
- [x] Implementation in React
