### ISSUE TITLE
🏭 Post/Thread View and Interaction

### ISSUE THREAD

**Issue by FurKay00** [SE-TINF22B6/DHBWhub#67]
Epic:
#43 
### Description
As a user, i want to interact or create posts on a focussed view.
### Tasks
I want this concrete feature so that I can interact easier with other people and focus on a single post/thread. 
These are the following criteria:

- [x] Figma mockup created
- [x] Implementation in React
- [x] Database schema implemented
